#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"

DATA_ROOT="${DATA_ROOT:-/mnt/disks/data}"
MODEL_DIR="${MODEL_DIR:-${DATA_ROOT}/models/Llama-3.1-8B}"
HF_HOME="${HF_HOME:-${DATA_ROOT}/hf-cache}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${DATA_ROOT}/outputs}"
VENV_DIR="${VENV_DIR:-${HOME}/nlp-re/.venv}"
PYTHON_BIN="${PYTHON_BIN:-python3.10}"
PYTORCH_INDEX_URL="${PYTORCH_INDEX_URL:-https://download.pytorch.org/whl/cu124}"
HF_TOKEN="${HF_TOKEN:-}"
MODEL_HF_REPO_ID="${MODEL_HF_REPO_ID:-meta-llama/Llama-3.1-8B}"
MODEL_REVISION="${MODEL_REVISION:-main}"
SAE_OUTPUT_DIR="${SAE_OUTPUT_DIR:-${OUTPUT_ROOT}/sae_eval_full}"
CAUSAL_OUTPUT_DIR="${CAUSAL_OUTPUT_DIR:-${OUTPUT_ROOT}/causal_validation_full}"
SAE_BATCH_SIZE="${SAE_BATCH_SIZE:-4}"
SAE_MAX_SEQ_LEN="${SAE_MAX_SEQ_LEN:-128}"
SAE_INFERENCE_MODE="${SAE_INFERENCE_MODE:-aligned_datasetwise}"
SAE_COMPARE_MEAN="${SAE_COMPARE_MEAN:-0}"
CAUSAL_BATCH_SIZE="${CAUSAL_BATCH_SIZE:-4}"
CAUSAL_MAX_SEQ_LEN="${CAUSAL_MAX_SEQ_LEN:-128}"
CAUSAL_LAMBDAS="${CAUSAL_LAMBDAS:-0.5 1.0 1.5 2.0}"
CAUSAL_N_BOOTSTRAP="${CAUSAL_N_BOOTSTRAP:-10}"
CAUSAL_SIDE_EFFECT_MAX_SAMPLES="${CAUSAL_SIDE_EFFECT_MAX_SAMPLES:-16}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
OPENAI_BASE_URL="${OPENAI_BASE_URL:-}"
OPENAI_MODEL="${OPENAI_MODEL:-}"

usage() {
  cat <<EOF
Usage:
  bash deploy/gce/configure_env.sh [options]

Options:
  --env-file PATH
  --data-root PATH
  --model-dir PATH
  --hf-home PATH
  --output-root PATH
  --venv-dir PATH
  --python-bin BIN
  --pytorch-index-url URL
  --hf-token TOKEN
  --model-hf-repo-id REPO
  --model-revision REV
  --sae-output-dir PATH
  --causal-output-dir PATH
  --sae-batch-size INT
  --sae-max-seq-len INT
  --sae-inference-mode legacy|aligned_datasetwise
  --sae-compare-mean 0|1
  --causal-batch-size INT
  --causal-max-seq-len INT
  --causal-lambdas "0.5 1.0 1.5 2.0"
  --causal-n-bootstrap INT
  --causal-side-effect-max-samples INT
  --openai-api-key KEY
  --openai-base-url URL
  --openai-model NAME
  --help

Example:
  bash deploy/gce/configure_env.sh \\
    --hf-token YOUR_TOKEN \\
    --data-root /mnt/disks/data \\
    --sae-inference-mode aligned_datasetwise
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file) ENV_FILE="$2"; shift 2 ;;
    --data-root) DATA_ROOT="$2"; shift 2 ;;
    --model-dir) MODEL_DIR="$2"; shift 2 ;;
    --hf-home) HF_HOME="$2"; shift 2 ;;
    --output-root) OUTPUT_ROOT="$2"; shift 2 ;;
    --venv-dir) VENV_DIR="$2"; shift 2 ;;
    --python-bin) PYTHON_BIN="$2"; shift 2 ;;
    --pytorch-index-url) PYTORCH_INDEX_URL="$2"; shift 2 ;;
    --hf-token) HF_TOKEN="$2"; shift 2 ;;
    --model-hf-repo-id) MODEL_HF_REPO_ID="$2"; shift 2 ;;
    --model-revision) MODEL_REVISION="$2"; shift 2 ;;
    --sae-output-dir) SAE_OUTPUT_DIR="$2"; shift 2 ;;
    --causal-output-dir) CAUSAL_OUTPUT_DIR="$2"; shift 2 ;;
    --sae-batch-size) SAE_BATCH_SIZE="$2"; shift 2 ;;
    --sae-max-seq-len) SAE_MAX_SEQ_LEN="$2"; shift 2 ;;
    --sae-inference-mode) SAE_INFERENCE_MODE="$2"; shift 2 ;;
    --sae-compare-mean) SAE_COMPARE_MEAN="$2"; shift 2 ;;
    --causal-batch-size) CAUSAL_BATCH_SIZE="$2"; shift 2 ;;
    --causal-max-seq-len) CAUSAL_MAX_SEQ_LEN="$2"; shift 2 ;;
    --causal-lambdas) CAUSAL_LAMBDAS="$2"; shift 2 ;;
    --causal-n-bootstrap) CAUSAL_N_BOOTSTRAP="$2"; shift 2 ;;
    --causal-side-effect-max-samples) CAUSAL_SIDE_EFFECT_MAX_SAMPLES="$2"; shift 2 ;;
    --openai-api-key) OPENAI_API_KEY="$2"; shift 2 ;;
    --openai-base-url) OPENAI_BASE_URL="$2"; shift 2 ;;
    --openai-model) OPENAI_MODEL="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

mkdir -p "$(dirname "${ENV_FILE}")"

write_var() {
  local key="$1"
  local value="${2-}"
  printf '%s=%q\n' "${key}" "${value}" >> "${ENV_FILE}"
}

: > "${ENV_FILE}"
echo "# Auto-generated by deploy/gce/configure_env.sh" >> "${ENV_FILE}"
write_var "DATA_ROOT" "${DATA_ROOT}"
write_var "MODEL_DIR" "${MODEL_DIR}"
write_var "HF_HOME" "${HF_HOME}"
write_var "OUTPUT_ROOT" "${OUTPUT_ROOT}"
echo >> "${ENV_FILE}"
write_var "VENV_DIR" "${VENV_DIR}"
write_var "PYTHON_BIN" "${PYTHON_BIN}"
write_var "PYTORCH_INDEX_URL" "${PYTORCH_INDEX_URL}"
echo >> "${ENV_FILE}"
write_var "HF_TOKEN" "${HF_TOKEN}"
write_var "MODEL_HF_REPO_ID" "${MODEL_HF_REPO_ID}"
write_var "MODEL_REVISION" "${MODEL_REVISION}"
echo >> "${ENV_FILE}"
write_var "SAE_OUTPUT_DIR" "${SAE_OUTPUT_DIR}"
write_var "CAUSAL_OUTPUT_DIR" "${CAUSAL_OUTPUT_DIR}"
echo >> "${ENV_FILE}"
write_var "SAE_BATCH_SIZE" "${SAE_BATCH_SIZE}"
write_var "SAE_MAX_SEQ_LEN" "${SAE_MAX_SEQ_LEN}"
write_var "SAE_INFERENCE_MODE" "${SAE_INFERENCE_MODE}"
write_var "SAE_COMPARE_MEAN" "${SAE_COMPARE_MEAN}"
echo >> "${ENV_FILE}"
write_var "CAUSAL_BATCH_SIZE" "${CAUSAL_BATCH_SIZE}"
write_var "CAUSAL_MAX_SEQ_LEN" "${CAUSAL_MAX_SEQ_LEN}"
write_var "CAUSAL_LAMBDAS" "${CAUSAL_LAMBDAS}"
write_var "CAUSAL_N_BOOTSTRAP" "${CAUSAL_N_BOOTSTRAP}"
write_var "CAUSAL_SIDE_EFFECT_MAX_SAMPLES" "${CAUSAL_SIDE_EFFECT_MAX_SAMPLES}"
echo >> "${ENV_FILE}"
write_var "OPENAI_API_KEY" "${OPENAI_API_KEY}"
write_var "OPENAI_BASE_URL" "${OPENAI_BASE_URL}"
write_var "OPENAI_MODEL" "${OPENAI_MODEL}"

echo "Wrote ${ENV_FILE}"
echo "Key settings:"
echo "  PROJECT_ROOT=${PROJECT_ROOT}"
echo "  DATA_ROOT=${DATA_ROOT}"
echo "  MODEL_DIR=${MODEL_DIR}"
echo "  OUTPUT_ROOT=${OUTPUT_ROOT}"
echo "  SAE_INFERENCE_MODE=${SAE_INFERENCE_MODE}"
echo "  SAE_OUTPUT_DIR=${SAE_OUTPUT_DIR}"
echo "  CAUSAL_OUTPUT_DIR=${CAUSAL_OUTPUT_DIR}"
echo
echo "Next steps:"
echo "  1. bash deploy/gce/bootstrap.sh"
echo "  2. bash deploy/gce/download_model.sh"
echo "  3. bash deploy/gce/run_full_eval.sh"
echo "  4. bash deploy/gce/run_causal.sh"
